# Generated by Django 2.1.7 on 2022-08-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('firmname', models.CharField(max_length=100)),
                ('firmwork', models.TextField()),
                ('firmaddress', models.TextField()),
                ('cpname', models.CharField(max_length=50)),
                ('cpcontactno', models.CharField(max_length=15)),
                ('cpemailaddress', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('aadharno', models.CharField(max_length=12)),
                ('panno', models.CharField(max_length=10)),
                ('gstno', models.CharField(max_length=15)),
                ('regdate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('address', models.TextField()),
                ('contactno', models.CharField(max_length=15)),
                ('emailaddress', models.EmailField(max_length=50)),
                ('enquirytext', models.TextField()),
                ('posteddate', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('address', models.TextField()),
                ('contactno', models.CharField(max_length=15)),
                ('emailaddress', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('dob', models.CharField(max_length=20)),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=20)),
                ('keyskills', models.TextField()),
                ('regdate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('usertype', models.CharField(max_length=50)),
            ],
        ),
    ]
