# Generated by Django 2.1.7 on 2022-09-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='id',
        ),
        migrations.AlterField(
            model_name='login',
            name='userid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
